### ISSUE TITLE
wrong handle of tab key and not handle mouse keys

### ISSUE THREAD

**Issue by moseschrist** [moseschrist/consoleproject#16]
#15 tab key should work as follows:
scroll inside your own list until the last option had been reached, then move to next list.

mouse clicks should allow direct focus change between lists.

**Comment by amitresh** [comment]
1. I don't understand you meaning about the TAB. We decided the TAB key returns the RETURN_TO_PARENT code and the upper level decides what to do. That's what I implemented. And my sample main() demonstrates this.
Is there still something wrong with the implementation?

2. I don't agree about the mouse clicks!  If there is a mouse click outside my controller I should return a NOT_MINE and let the upper level decide what to do -- NOT(!) do a focus change directly ... its not my job to know who the "next" controller is!

**Comment by moseschrist** [comment]
1. the TAB key can have different meaning in every control, in every UI
system i know, the radio and checkbox act the following way:
tab scrolls through it's options, when reaching the last it moves to the
next control.

2. the mouse clicks, i agree but for only for now, until we have a desktop
"control" to handle that.

**Comment by amitresh** [comment]
1. Fixed TAB, as you defined. Pull and verify.

2. What do you mean "only for now" -- for always. After we have a desktop controller it will still be implemented this way -- and 3verything should be good ...

**Comment by moseschrist** [comment]
because the desktop should know how to interpret that "not_mine" answer and
handle it correctly. that is what i mean "for now"

**Comment by moseschrist** [comment]
the tab key is still wrong,
after the end of the second list you should jump to the first item in the
first list.

**Comment by amitresh** [comment]
I decided on a policy of remembering the last selection on a controller before focus was taken and going back to that when focus returns. Do you think that is wrong? Should giving focus ALWAYS return to the topmost option?

**Comment by moseschrist** [comment]
Not always, it depends on the control. For this one, I believe this is the
correct way.
